---
# ---------------
# Package Sources
# ---------------

#
# TODO: 2.6 repository no longer exists we have to install cobbler from sources.
# https://gist.github.com/kvnkuo/9087e5112035477dd959b53ef51dba4a
#

#- name: import cobbler key
#  apt_key:  url="{{ cobbler_ubuntu_repo_url }}/Release.key" state=absent
#  when: cobbler_manage_repo
#
#- name: import cobbler repo
#  apt_repository: repo='deb {{ cobbler_ubuntu_repo_url }}/ ./' state=absent
#  when: cobbler_manage_repo

# ------------
# Dependencies
# ------------
#
# HACK: Cobbler ubuntu deb package is still asking for python-support dependency
#       which is no longer provided in ubuntu 16.04 as they moved away
#       from python2.7 to python3
#- name: Fix missing package for cobbler version => 2.8
#  apt: deb="{{ cobbler_ubuntu_dependiences_fix }}" state=present
#  when: ansible_lsb.major_release >= 16

- name: install dependencies (apt)
  package:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
    update_cache: yes
  with_items:
    - xinetd
    - isc-dhcp-server
    - debmirror
    - libapache2-mod-python
    - libapache2-mod-proxy-uwsgi
    - fence-agents
    - tftpd-hpa

# ---------------
# isc-dhcp-server
# ---------------
- name: configure isc-dhcp-server (apt)
  template:
    src: isc-dhcp-server.j2
    dest: /etc/default/isc-dhcp-server

- name: enable isc-dhcp-server (apt)
  service:
    name: isc-dhcp-server
    state: stopped
    enabled: yes
