---
# ------------
# Dependencies
# ------------

- name: install dependencies (apt)
  package:
    name: "{{ cobbler_system_dependiences }}"
    cache_valid_time: 3600
    update_cache: yes
    state: present

# ---------------
# isc-dhcp-server
# ---------------
- name: configure isc-dhcp-server (apt)
  template:
    src: isc-dhcp-server.j2
    dest: /etc/default/isc-dhcp-server
  notify:
    - restart dhcp

- name: enable isc-dhcp-server (apt)
  service:
    name: isc-dhcp-server
    state: started
    enabled: yes
