---

# ---------
# firewalld
# ---------
- name: check if firewalld is installed
  command: which firewalld
  register: firewalld
  changed_when: false
  ignore_errors: true
  check_mode: false

- name: check if firewalld service is running
  command: firewall-cmd --state
  register: firewalld_svc
  ignore_errors: true
  check_mode: false
  when: firewalld is success

- name: enable cobbler tftpd through firewalld
  firewalld:
    service: tftp
    permanent: true
    state: enabled
  notify: restart firewalld
  when: firewalld is success and firewalld_svc.stdout == 'running'

- name: enable cobbler httpd through firewalld
  firewalld:
    service: http
    permanent: true
    state: enabled
  notify: restart firewalld
  when: firewalld is success and firewalld_svc.stdout == 'running'

# ---
# ufw
# ---
- name: check if ufw is installed
  command: which ufw
  register: ufw
  changed_when: false
  ignore_errors: true

- name: allow tftp through ufw
  ufw:
    rule: allow
    port: 69
    proto: tcp
  when: ufw is success

- name: allow http through ufw
  ufw:
    rule: allow
    port: 80
    proto: tcp
  when: ufw is success