---
# file: main.yml
# The tasks for the Cobbler role

# -------------
# Prerequisites
# -------------

- name: unsupported package manager
  fail:
    msg: this playbook requries RedHat or Debian based system
  when: ansible_os_family|lower != 'redhat' and ansible_os_family|lower != 'debian'

- name: Include OS required variables
  include_vars: '{{ ansible_os_family | lower }}.yml'

- name: Include OS specific tasks
  include: '{{ ansible_os_family | lower }}.yml'

- import_tasks: firewall.yml

# ---------------------
# Cobbler Install
# ---------------------
- name: create required directories
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    recurse: yes
    state: directory
  with_items:
    - path: /var/lib/cobbler/webui_sessions
      owner: www-data
      group: www-data
    - path: /etc/cobbler
    - path: /var/log/cobbler

- name: install cobbler from pip
  pip:
    name: "{{ item }}"
#    version: v2.8.4
    state: present

    virtualenv_command: virtualenv
    virtualenv_python: python2.7
    virtualenv: "{{ cobbler_install_dir }}"
  with_items:
    - Cheetah
    - netaddr
    - simplejson
    - urlgrabber
    - PyYAML
    - django
    - pycurl
    - "git+https://github.com/cobbler/cobbler.git@{{ cobbler_version }}#egg=cobbler"
  register: _cobbler_installed

#- name: Copy files from site-packages to right places
#  command: rsync -avc --exclude {{ item.src }} {{ item.dest }}
#  with_items:
#    - src: "{{ cobbler_install_dir }}/lib/python2.7/site-packages/etc/cobbler"
#      dest: /etc/
#    - src: "{{ cobbler_install_dir }}/lib/python2.7/site-packages/srv/www"
#      dest: /srv/
#    - src: "{{ cobbler_install_dir }}/lib/python2.7/site-packages/var/lib/cobbler"
#      dest: /var/lib/
#    - src: "{{ cobbler_install_dir }}/lib/python2.7/site-packages/share/cobbler"
#      dest: /usr/share/cobbler

- name: enable required apache modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - proxy
    - proxy_http
    - status
    - rewrite
  notify:
    - restart apache

- name: Copy cobbler installation files
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: files/etc/cobbler
      dest: /etc/
    - src: files/srv/www
      dest: /srv/
    - src: files/var/lib/cobbler
      dest: /var/lib/
    - src: files/sbin/
      dest: /usr/local/sbin
    - src: files/usr/share/cobbler
      dest: /usr/share/
    when: _cobbler_installed is changed or cobbler_sync_files

- name: Create required directories
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
    - /var/log/cobbler/tasks
    - /var/lib/cobbler/loaders
    - /srv/cobbler/iso

- name: copy cobbler apache config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
  with_items:
    - src: cobbler.conf.j2
      dest: "/etc/{{ apache_service_name }}/conf-enabled/cobbler.conf"
      mode: 0644
    - src: cobbler_web.conf.j2
      dest: "/etc/{{ apache_service_name }}/conf-enabled/cobbler_web.conf"
      mode: 0644
    - src: rsync.j2
      dest: /etc/xinetd.d/rsync
      owner: root
      group: root
      mode: 0644
    - src:  cobblerd.service.j2
      dest: /etc/systemd/system/cobblerd.service
      mode: 0644
  notify:
    - reload systemd
    - restart apache
    - restart xinetd

- meta: flush_handlers

- name: configure cobbler
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items:
    - src: settings.j2
      dest: /etc/cobbler/settings
    - src: dhcp.template.j2
      dest: /etc/cobbler/dhcp.template
  notify:
    - restart cobbler
    - wait for cobbler
    - sync cobbler

- meta: flush_handlers

- name: start and enable xinetd, apache2, cobbler
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - xinetd
    - "{{ apache_service_name }}"
    - "{{ daemon }}"

- name: wait for cobbler
  wait_for:
    host: 127.0.0.1
    port: 25151
    delay: 5
    timeout: 30
    state: started

# ---------------------
# Cobbler Preload data
# ---------------------

- name: get cobbler loaders
  shell: "{{ cobbler_bin }} get-loaders"
  args:
    creates: /var/lib/cobbler/loaders/README
  when: cobbler_get_loaders
  notify:
    - restart cobbler
    - wait for cobbler
    - sync cobbler

- name: update cobbler signatures
  shell: "{{ cobbler_bin }} signature update"
  when: cobbler_signature_update
  notify:
    - restart cobbler
    - wait for cobbler
    - sync cobbler

# ---------------------
# Cobbler Kickstarts
# ---------------------

- name: adding default ubuntu preseed
  template:
    src: ubuntu-server.preseed.j2
    dest: /etc/cobbler/ubuntu-server.preseed

- name: copy user defined kickstart files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items: "{{ kickstarts }}"
  notify:
    - restart cobbler

# ---------------------
# Cobbler Distributions
# ---------------------

# Attempt to un-mount any previous disto mount points, can occur if previous run failed
- name: umount isos
  ignore_errors: yes
  shell: umount {{ item.path | quote }}
  with_items:
    - "{{ distros }}"
  when: distros is defined

# Download each defined distro ISO if it doesn't already exist
- name: download distro iso files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.file }}"
  with_items:
    - "{{ distros }}"
  when: distros is defined

# Add the each distro/profile pair only if the distro doesn't already exist
- name: check distro exists in cobbler
  shell: "{{ cobbler_bin }} distro report --name={{ item.name | quote }}-{{ item.arch | quote }} > /dev/null"
  ignore_errors: yes
  changed_when: no
  register: distro_result
  when: distros is defined
  with_items:
    - "{{ distros }}"

- debug:
    msg: "Distro watch {{ distro_result }}"

- name: add distro/profile pairs to cobbler
  shell: >
    (mkdir -p {{ item.path | quote }}
    && mount -t iso9660 -o loop,ro {{ item.file | quote }} {{ item.path | quote }}
    && {{ cobbler_bin }} import --path={{ item.path | quote }} --name={{ item.name | quote }} --arch={{ item.arch | quote }} {% if item.kickstart is defined %}--kickstart={{ item.kickstart | quote }}{% endif %}
    && umount {{ item.path | quote }})
  with_items:
    - "{{ distros }}"
  when: distros is defined and distro_result is failed
  notify:
    - restart cobbler
    - wait for cobbler
    - sync cobbler

- name: edit distro repos if needed
  shell: >
    {{ cobbler_bin }} repo edit --name="{{ item.name}}-{{ item.arch }}"
    {% if item.repo_settings.apt_components is defined %}--apt_components={{ item.repo_settings.apt_components | quote }}{% endif %}
    {% if item.repo_settings.apt_dists is defined %}--apt_dists={{ item.repo_settings.apt_dists | quote }}{% endif %}
  with_items:
    - "{{ distros }}"
  when: distros is defined and item.repo_settings is defined
  notify:
    - sync cobbler

#- name: check distro for import exists in cobbler
#  with_items: distro_imports
#  command: {{ cobbler_bin }} distro report --name="{{ item.name }}"
#  register: distro_imports_result
#  ignore_errors: true
#  when: distro_imports is defined

#- name: import distro to cobbler
#  shell: {{ cobbler_bin }} import --name="{{ item.name }}-{{ item.arch }}" --path="{{ item.url }}" --arch="{{ item.arch }}"
#  with_items: distro_imports
#  when: distro_imports is defined and distro_imports_result|failed
#  notify:
#    - restart cobbler
#    - wait for cobbler
#    - sync cobbler

# ---------------
# Cobbler Repos
# ---------------

- name: add repos to cobbler
  shell: >
    {{ cobbler_bin }} repo add
    --clobber
    --name={{ item.name | quote }}
    --mirror={{ item.mirror | quote }}
    {% if item.arch is defined %}--arch={{ item.arch | quote }}{% endif %}
    {% if item.mirror_locally is defined %}--mirror-locally={{ item.mirror_locally | quote }}{% endif %}
  when: repos is defined
  with_items:
    - "{{ repos }}"
  notify:
    - restart cobbler
    - wait for cobbler
    - sync cobbler

# ---------------
# Cobbler Profiles
# ---------------

- name: add profiles to cobbler
  shell: >
    {{ cobbler_bin }} profile add
    --clobber
    --name={{ item.name | quote }}
    --distro={{ item.distro | quote }}
    {% if item.kickstart is defined %}--kickstart={{ item.kickstart | quote }}{% endif %}
    {% if item.ksmeta is defined %}--ksmeta={{ item.ksmeta | quote }}{% endif %}
    {% if item.kopts is defined %}--kopts={{ item.kopts | quote }}{% endif %}
    {% if item.kopts_post is defined %}--kopts-post={{ item.kopts_post | quote }}{% endif %}
    {% if item.repos is defined %}--repos={{ item.repos | quote }}{% endif %}
  when: profiles is defined
  with_items:
    - "{{ profiles }}"
  notify:
    - restart cobbler
    - wait for cobbler
    - sync cobbler

# ---------------
# Cobbler Systems
# ---------------

- debug: var=systems

- name: add systems to cobbler
  shell: >
    {{ cobbler_bin }} system add
    --clobber
    --name={{ item.name | quote }}
    --hostname={{ item.hostname | default(item.name) | quote }}
    --profile={{ item.profile | quote }}
    --ip-address={{ item.ip | quote }}
    --subnet={{ item.netmask | quote }}
    --gateway={{ item.gateway | quote }}
    --mac={{ item.mac | quote }}
    --interface={{ item.interface | quote }}
    {% if item.netboot is defined %}--netboot-enabled={{ item.netboot | quote }}{% endif %}
    {% if item.dns_name is defined %}--dns-name={{ item.dns_name | quote }}{% endif %}
    {% if item.static is defined %}--static={{ item.static }}{% endif %}
    {% if item.kopts is defined %}--kopts={{ item.kopts | quote }}{% endif %}
    {% if item.kopts_post is defined %}--kopts-post={{ item.kopts_post | quote }}{% endif %}
    {% if item.ksmeta is defined %}--ksmeta={{ item.ksmeta | quote }}{% endif %}
    {% if item.dhcptag is defined %}--dhcp-tag={{ item.dhcptag | quote }}{% endif %}
    {% if item.next_server is defined %}--server={{ item.next_server | quote }}{% endif %}
    {% if item.mgmt_classes is defined %}--mgmt-classes={{ item.mgmt_classes | quote }}{% endif %}
  when: systems is defined
  with_items:
    - "{{ systems }}"
  notify:
    - restart cobbler
    - wait for cobbler
    - sync cobbler
