---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: cobbler-1
    box: ubuntu/bionic64
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH:
      $ephemeral_directory/roles/:$project_root/../
    ANSIBLE_PYTHON_INTERPRETER:
      /usr/bin/python3
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  directory: ./tests
  lint:
    name: flake8

